### KNN MODEL

In [1]:
## get the model
from sklearn.neighbors import KNeighborsClassifier

In [20]:
## instantiate the model
model1=KNeighborsClassifier()

In [21]:
model1

KNeighborsClassifier()

In [22]:
## get the dataset
import numpy as np
np.random.seed(20)
weights=np.random.randint(40,120,50)

In [23]:
weights

array([ 55,  68,  49,  60, 115,  62, 111,  74,  80,  66,  56, 102,  56,
        47,  46,  66,  53, 115,  98,  65,  43, 114, 115, 101, 117,  97,
        72,  50,  46, 115,  58,  43, 117,  57,  83,  56,  58, 119,  99,
       111, 115,  69,  85,  46, 103, 118,  64,  58,  73, 118])

In [24]:
np.random.seed(20)
gender=np.random.randint(0,2,50)

In [25]:
gender # 0 for female and 1 for male

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1])

In [26]:
# weights=feature=independent variable (This is assigned 'X')
# gender=target=label=dependent (This is assigned 'y')

In [27]:
X=weights # this is meant to be a 2 dimensional arrat
y=gender # this should be 1 dimensional

In [19]:
# Train the model
model1.fit(X,y)

ValueError: Expected 2D array, got 1D array instead:
array=[ 55  68  49  60 115  62 111  74  80  66  56 102  56  47  46  66  53 115
  98  65  43 114 115 101 117  97  72  50  46 115  58  43 117  57  83  56
  58 119  99 111 115  69  85  46 103 118  64  58  73 118].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [28]:
X=X.reshape(-1,1)

In [29]:
model1.fit(X,y)

KNeighborsClassifier()

In [30]:
model1.predict([[89]])

array([1])

In [31]:
model1.predict([[40]])

array([0])

In [37]:
model1.predict([[56]])

array([1])

In [36]:
model1.predict([[80]])

array([1])