In [4]:
import pandas as pd

In [6]:
df=pd.read_csv("train.csv")

In [7]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
# All the headings here which are the charactyeristics are called features. In this case, we want to predicts survived so survived is not a feature but a label/target

In [9]:
X=df.Age

In [10]:
X # feature metrix

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [11]:
y=df.Survived

In [12]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [13]:
X.shape
X.ndim # used to check the number of dimensions

(891,)

In [14]:
y.shape

(891,)

In [15]:
X=X.reshape(-1,1)

AttributeError: 'Series' object has no attribute 'reshape'

In [17]:
X.isna().sum()

177

In [23]:
X=X.fillna(method="ffill")

In [24]:
X.isna().sum()

0

In [25]:
type(X)

pandas.core.series.Series

In [27]:
X=X.values

In [29]:
type(X)

numpy.ndarray

In [30]:
X=X.reshape(-1,1)

In [31]:
X

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [35.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [ 2.  ],
       [31.  ],
       [31.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [38.  ],
       [19.  ],
       [19.  ],
       [19.  ],
       [40.  ],
       [40.  ],
       [40.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [42.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [27.  ],
       [ 3.  ],
       [19.  ],
       [19.  ],
       [19.  ],
       [19.  ],
       [19.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [65.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [32]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier()
knn

KNeighborsClassifier()

In [33]:
knn.fit(X,y)

KNeighborsClassifier()

In [35]:
knn.predict([[50]])

array([0], dtype=int64)

In [36]:
knn.predict([[70]])

array([0], dtype=int64)

In [37]:
knn.predict([[27]])

array([1], dtype=int64)

In [38]:
knn.score(X,y)

0.6083052749719416