In [1]:
a=[2,4,5]

In [2]:
import math

In [3]:
math.sin(4)

-0.7568024953079282

In [4]:
math.cos(a[2])

0.28366218546322625

In [5]:
import numpy as np

In [6]:
a1=np.array(a)

In [7]:
np.sin(a1)

array([ 0.90929743, -0.7568025 , -0.95892427])

In [8]:
np.cos(a1)

array([-0.41614684, -0.65364362,  0.28366219])

In [9]:
np.tan(a1)

array([-2.18503986,  1.15782128, -3.38051501])

In [10]:
np.abs(a)

array([2, 4, 5])

### Statistics

In [11]:
np.mean(a1)

3.6666666666666665

In [12]:
np.sum(a1)

11

In [13]:
np.min(a1)

2

In [14]:
np.argmax(a1)

2

In [15]:
np.argmin(a1)

0

### Agrregate function: 
### Is a universal value that retruns one function

In [16]:
np.std(a1)

1.247219128924647

In [17]:
np.var(a1, ddof=1)

2.333333333333333

In [20]:
scores=np.random.randint(0,10,10)

In [21]:
scores=np.random.randint(0,100,(3,4))

In [22]:
scores

array([[93, 92, 52,  3],
       [85, 83, 20, 73],
       [26, 59, 47, 97]])

In [23]:
np.mean(scores)

60.833333333333336

In [24]:
scores.mean()

60.833333333333336

In [25]:
np.median(scores)

66.0

## Axis

In [26]:
np.sum(scores)

730

In [27]:
np.sum(scores, axis=0) #sum down the column

array([204, 234, 119, 173])

In [28]:
np.sum(scores, axis=1) #sum across the row

array([240, 261, 229])

In [29]:
np.mean(scores,axis=0)

array([68.        , 78.        , 39.66666667, 57.66666667])

In [30]:
np.argmax(np.mean(scores,axis=0))

1

In [31]:
scores

array([[93, 92, 52,  3],
       [85, 83, 20, 73],
       [26, 59, 47, 97]])

In [32]:
np.argmin(np.mean(scores,axis=0))

2

### Broadcasting

In [33]:
a1

array([2, 4, 5])

In [34]:
a1+2

array([4, 6, 7])

In [35]:
a1*3

array([ 6, 12, 15])

In [36]:
x=np.linspace(10,100,7)

In [37]:
x

array([ 10.,  25.,  40.,  55.,  70.,  85., 100.])

In [38]:
y=np.arange(10,100,7)

In [39]:
y

array([10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94])

In [42]:
y=np.linspace(20,70,3)

In [43]:
y

array([20., 45., 70.])

In [44]:
x+y

ValueError: operands could not be broadcast together with shapes (7,) (3,) 

In [45]:
z=np.random.randint(12,200,9)

In [46]:
z

array([ 46,  80,  42,  89, 101, 153,  32,  80, 147])

In [47]:
y+z

ValueError: operands could not be broadcast together with shapes (3,) (9,) 

In [48]:
z.shape

(9,)

In [49]:
z.shape=(3,3)

In [50]:
z

array([[ 46,  80,  42],
       [ 89, 101, 153],
       [ 32,  80, 147]])

In [51]:
z+y

array([[ 66., 125., 112.],
       [109., 146., 223.],
       [ 52., 125., 217.]])

In [52]:
y

array([20., 45., 70.])

In [53]:
y1=y[:2]

In [67]:
y1

array([20., 45.])

In [68]:
a1=np.random.randint(1,10,(2,3))

In [69]:
a1

array([[6, 7, 2],
       [6, 7, 2]])

In [70]:
b1=np.random.randint(1,10,(1,3))

In [71]:
b1

array([[3, 8, 8]])

In [72]:
b2=np.random.randint(1,10,(2,1))

In [73]:
b2

array([[3],
       [4]])

In [74]:
a1+b2

array([[ 9, 10,  5],
       [10, 11,  6]])

In [75]:
a1+b1

array([[ 9, 15, 10],
       [ 9, 15, 10]])

In [79]:
b3=np.random.randint(1,2,(2,2))

In [80]:
b3

array([[1, 1],
       [1, 1]])

In [81]:
a1+b3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [86]:
a2=np.random.randint(2,12,(4,2))

In [87]:
a2

array([[ 6,  9],
       [11,  3],
       [ 3,  7],
       [10,  5]])

In [88]:
b3

array([[1, 1],
       [1, 1]])

In [89]:
a2+b3

ValueError: operands could not be broadcast together with shapes (4,2) (2,2) 