## Splitting and joining of Arrays

In [2]:
import numpy as np

In [4]:
x=np.linspace(10,20,8)

In [5]:
x

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        ])

In [6]:
x[0]

10.0

In [7]:
x[-1]

20.0

### nested list/array
### python review

In [8]:
a=[[2,4,5],[5,6,7]]

In [9]:
len(a)

2

In [10]:
a[0]

[2, 4, 5]

In [13]:
a[1][1]

6

In [16]:
a1=np.array(a)

In [17]:
a1

array([[2, 4, 5],
       [5, 6, 7]])

In [18]:
a1[0]

array([2, 4, 5])

In [19]:
a1[1][1]

6

In [20]:
a1[1,1]

6

In [21]:
x

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        ])

In [23]:
x[0:3]

array([10.        , 11.42857143, 12.85714286])

In [24]:
x[:3]

array([10.        , 11.42857143, 12.85714286])

In [25]:
x[:5:2]

array([10.        , 12.85714286, 15.71428571])

### N/B Slicing takes 3 values: where you start from, where you want to stop and the step size

In [26]:
x[:5:2]

array([10.        , 12.85714286, 15.71428571])

In [27]:
a1

array([[2, 4, 5],
       [5, 6, 7]])

In [28]:
a1[:,2] ## gives all th rows in column 2

array([5, 7])

In [29]:
a1[:,1:3]

array([[4, 5],
       [6, 7]])

In [30]:
a1[:,0:2]

array([[2, 4],
       [5, 6]])

In [31]:
a1[:,0:1]

array([[2],
       [5]])

In [33]:
y=np.random.randint(2,20,(4,5))

In [34]:
y

array([[13,  7, 10,  5,  2],
       [19, 17, 15, 11, 16],
       [15, 13,  3, 13,  7],
       [ 9, 19, 10,  6, 12]])

In [35]:
y[:2]

array([[13,  7, 10,  5,  2],
       [19, 17, 15, 11, 16]])

In [36]:
y[-2:,1:3]

array([[13,  3],
       [19, 10]])

In [37]:
y[2:4,1:3]

array([[13,  3],
       [19, 10]])

### Fancy indexing

In [39]:
x

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        ])

In [40]:
x[::2]

array([10.        , 12.85714286, 15.71428571, 18.57142857])

In [43]:
x[[0,2,6]]

array([10.        , 12.85714286, 18.57142857])

In [44]:
y

array([[13,  7, 10,  5,  2],
       [19, 17, 15, 11, 16],
       [15, 13,  3, 13,  7],
       [ 9, 19, 10,  6, 12]])

In [45]:
y[[0,1,2],[0,1,2]]

array([13, 17,  3])

In [48]:
y[[0,2,3],[0,3,3]]

array([13, 13,  6])

 ## Loading datasets

In [50]:
file=open("grad_survey.csv", "r")
content=file.read()
file.close()
print(content)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [52]:
file=open("grad_survey.csv", "r")
for row in file.readlines()[:10]:
    print(row)

Timestamp,What is your gender,Year of graduation,Title of course studied,Polytechnic/University attended,What is your highest level of education?,What best describes your current status?,How many jobs have you had since graduation including your current one?,Have you completed your NYSC?,"If you answered yes/ongoing to the previous question, what year did you (or will you) complete your NYSC?",Did you get your first full time job through your NYSC placement?,"Thinking about your first employment after graduation, what was your job level?",What is/was your job role?,"What sector/industry is your company in? (E.g. Banking, Agriculture, Telecommunication)","Still thinking about your first employment, what is/was your monthly income level?","Did you need your higher education qualification to get your first job (the actual qualification, not the subject of study)?",What was the most significant reason for deciding to take your first job?,"Thinking about your current employment, what is you

In [53]:
result=[]
file=open("grad_survey.csv", "r")
for row in file.readlines()[:10]:
    result.append(row)
file.close()
print(result)

['Timestamp,What is your gender,Year of graduation,Title of course studied,Polytechnic/University attended,What is your highest level of education?,What best describes your current status?,How many jobs have you had since graduation including your current one?,Have you completed your NYSC?,"If you answered yes/ongoing to the previous question, what year did you (or will you) complete your NYSC?",Did you get your first full time job through your NYSC placement?,"Thinking about your first employment after graduation, what was your job level?",What is/was your job role?,"What sector/industry is your company in? (E.g. Banking, Agriculture, Telecommunication)","Still thinking about your first employment, what is/was your monthly income level?","Did you need your higher education qualification to get your first job (the actual qualification, not the subject of study)?",What was the most significant reason for deciding to take your first job?,"Thinking about your current employment, what is y

In [54]:
len(result)

10

In [59]:
captions=result[0]

In [61]:
captions

'Timestamp,What is your gender,Year of graduation,Title of course studied,Polytechnic/University attended,What is your highest level of education?,What best describes your current status?,How many jobs have you had since graduation including your current one?,Have you completed your NYSC?,"If you answered yes/ongoing to the previous question, what year did you (or will you) complete your NYSC?",Did you get your first full time job through your NYSC placement?,"Thinking about your first employment after graduation, what was your job level?",What is/was your job role?,"What sector/industry is your company in? (E.g. Banking, Agriculture, Telecommunication)","Still thinking about your first employment, what is/was your monthly income level?","Did you need your higher education qualification to get your first job (the actual qualification, not the subject of study)?",What was the most significant reason for deciding to take your first job?,"Thinking about your current employment, what is yo

In [65]:
splitted_captions=captions.split(",")

In [66]:
splitted_captions

['Timestamp',
 'What is your gender',
 'Year of graduation',
 'Title of course studied',
 'Polytechnic/University attended',
 'What is your highest level of education?',
 'What best describes your current status?',
 'How many jobs have you had since graduation including your current one?',
 'Have you completed your NYSC?',
 '"If you answered yes/ongoing to the previous question',
 ' what year did you (or will you) complete your NYSC?"',
 'Did you get your first full time job through your NYSC placement?',
 '"Thinking about your first employment after graduation',
 ' what was your job level?"',
 'What is/was your job role?',
 '"What sector/industry is your company in? (E.g. Banking',
 ' Agriculture',
 ' Telecommunication)"',
 '"Still thinking about your first employment',
 ' what is/was your monthly income level?"',
 '"Did you need your higher education qualification to get your first job (the actual qualification',
 ' not the subject of study)?"',
 'What was the most significant reason

In [67]:
type(captions)

str

In [69]:
ind_1=result[1]

In [70]:
ind_1

'2/8/2018 9:05:23,Male,2013,Electrical & Electronic Engineering,"Obafemi Awolowo University,Ile-Ife",Bachelor\'s degree,Working full time (paid employment),3,,,,Experience,,Technology,"‎₦50,000 - ‎₦99,999",No: the qualification was not required,It fitted into my career plan/it was exactly the type of work I wanted,Managerial,,Technology,"‎₦200,000 - ‎₦249,999",,It fitted into my career plan/it was exactly the type of work I wanted,NNPC,,Engineering,Naira,8,No one thing was important,Internship,No,Bus,Yes: From my first job,No,No,"Critical thinking skills, Ability to solve complex problems, Written communication skills, Spoken communication skills"\n'

### Study the csv model and know how to use it