## Numpy and Matplotlib

In [2]:
x=[2,0.5,(2,3)]

In [3]:
type(x[0])

int

In [4]:
type(x[1])

float

In [5]:
type(x[2])

tuple

In [6]:
a=[2,4,6]
b=[9,4,6]
print(a+b) #extending the list or concatenation

[2, 4, 6, 9, 4, 6]


In [8]:
c=[]
for i in range(3):
    c.append(a[i]+b[i])
print(c)

[11, 8, 12]


In [9]:
import numpy as np

In [10]:
a1=np.array(a)

In [11]:
a1

array([2, 4, 6])

In [12]:
b1=np.array(b)

In [13]:
b1

array([9, 4, 6])

In [15]:
a1+b1

array([18,  8, 12])

In [16]:
a1*b1

array([81, 16, 36])

In [17]:
a1%2

array([1, 0, 0], dtype=int32)

In [18]:
a1//2

array([4, 2, 3], dtype=int32)

In [19]:
a1.shape

(3,)

In [21]:
c1=np.array([[1,3,5],[4,5,3]])

In [22]:
c1.shape

(2, 3)

In [23]:
a1.ndim

1

In [24]:
c1.ndim

2

In [25]:
a1.size

3

In [26]:
c1.size

6

In [27]:
d=np.array([3,8,1.4])

In [28]:
d

array([3. , 8. , 1.4])

In [29]:
d.dtype

dtype('float64')

In [31]:
a1.dtype

dtype('int32')

## Other ways to form arrays

In [32]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])